### ISSUE TITLE
me too

### ISSUE THREAD

**Issue by qiurigao** [DroidThug/android_device_lenovo_karate#1]
my phone is vivo y55 MSM8937_32.
i can boot TWRP but my not device file
you can help me ?

**Comment by DroidThug** [comment]
I can help you, you may contact me on Telegram 

https://t.me/droidthug

Please don't open issues unrelated to this device.

**Comment by qiurigao** [comment]
@DroidThug  OK,Sorry

**Comment by DroidThug** [comment]
No problem :wink:

**Comment by qiurigao** [comment]
i not send tg.....
my id:qiurigao

**Comment by qiurigao** [comment]
![_20170520_202529](https://cloud.githubusercontent.com/assets/22121479/26275865/2be8bfe4-3d30-11e7-9405-1a26dec3bdf2.jpg)

**Comment by DroidThug** [comment]
![Image](http://i.imgur.com/sA2DGf9.png)

**Comment by qiurigao** [comment]
https://t.me/wellqrg
